package com.contentsquare.android.core.features.config.model;

import com.contentsquare.android.core.features.config.model.JsonConfig;
import com.contentsquare.android.core.utils.JsonConfigFeatureFlagNames;
import com.contentsquare.android.error.analysis.apierror.v2.EventProcessorPerformanceManager;
import com.urbanairship.AirshipConfigOptions;
import java.util.List;
import kotlin.Deprecated;
import kotlin.DeprecationLevel;
import kotlin.Metadata;
import kotlin.ReplaceWith;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.BooleanSerializer;
import kotlinx.serialization.internal.FloatSerializer;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.IntSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;
import org.jetbrains.annotations.NotNull;

@Metadata(d1 = {"\u00006\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\u0011\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0002\bÇ\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001B\u0007\b\u0002¢\u0006\u0002\u0010\u0003J\u0018\u0010\b\u001a\f\u0012\b\u0012\u0006\u0012\u0002\b\u00030\n0\tHÖ\u0001¢\u0006\u0002\u0010\u000bJ\u0011\u0010\f\u001a\u00020\u00022\u0006\u0010\r\u001a\u00020\u000eHÖ\u0001J\u0019\u0010\u000f\u001a\u00020\u00102\u0006\u0010\u0011\u001a\u00020\u00122\u0006\u0010\u0013\u001a\u00020\u0002HÖ\u0001R\u0014\u0010\u0004\u001a\u00020\u00058VXÖ\u0005¢\u0006\u0006\u001a\u0004\b\u0006\u0010\u0007¨\u0006\u0014"}, d2 = {"com/contentsquare/android/core/features/config/model/JsonConfig.ProjectConfiguration.$serializer", "Lkotlinx/serialization/internal/GeneratedSerializer;", "Lcom/contentsquare/android/core/features/config/model/JsonConfig$ProjectConfiguration;", "()V", "descriptor", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "getDescriptor", "()Lkotlinx/serialization/descriptors/SerialDescriptor;", "childSerializers", "", "Lkotlinx/serialization/KSerializer;", "()[Lkotlinx/serialization/KSerializer;", "deserialize", "decoder", "Lkotlinx/serialization/encoding/Decoder;", "serialize", "", "encoder", "Lkotlinx/serialization/encoding/Encoder;", "value", "core_release"}, k = 1, mv = {1, 8, 0}, xi = 48)
@Deprecated(level = DeprecationLevel.HIDDEN, message = "This synthesized declaration should not be used directly", replaceWith = @ReplaceWith(expression = "", imports = {}))
/* loaded from: classes2.dex */
public final class JsonConfig$ProjectConfiguration$$serializer implements GeneratedSerializer<JsonConfig.ProjectConfiguration> {

    @NotNull
    public static final JsonConfig$ProjectConfiguration$$serializer INSTANCE;
    private static final /* synthetic */ PluginGeneratedSerialDescriptor descriptor;

    static {
        JsonConfig$ProjectConfiguration$$serializer jsonConfig$ProjectConfiguration$$serializer = new JsonConfig$ProjectConfiguration$$serializer();
        INSTANCE = jsonConfig$ProjectConfiguration$$serializer;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("com.contentsquare.android.core.features.config.model.JsonConfig.ProjectConfiguration", jsonConfig$ProjectConfiguration$$serializer, 18);
        pluginGeneratedSerialDescriptor.addElement("enabled", false);
        pluginGeneratedSerialDescriptor.addElement(EventProcessorPerformanceManager.LOG_EVENT_ENDPOINT, false);
        pluginGeneratedSerialDescriptor.addElement("sample", false);
        pluginGeneratedSerialDescriptor.addElement("bucket", false);
        pluginGeneratedSerialDescriptor.addElement("crash_handler", false);
        pluginGeneratedSerialDescriptor.addElement("session_timeout", false);
        pluginGeneratedSerialDescriptor.addElement("opt_out_by_default", false);
        pluginGeneratedSerialDescriptor.addElement("client_mode", false);
        pluginGeneratedSerialDescriptor.addElement("in_app_config", true);
        pluginGeneratedSerialDescriptor.addElement("session_replay", true);
        pluginGeneratedSerialDescriptor.addElement(AirshipConfigOptions.FEATURE_FEATURE_FLAGS, true);
        pluginGeneratedSerialDescriptor.addElement("encryption_public_key_id", true);
        pluginGeneratedSerialDescriptor.addElement("encryption_public_key", true);
        pluginGeneratedSerialDescriptor.addElement(JsonConfigFeatureFlagNames.API_ERRORS, true);
        pluginGeneratedSerialDescriptor.addElement("api_errors_troubleshooting_v2", true);
        pluginGeneratedSerialDescriptor.addElement("webview", true);
        pluginGeneratedSerialDescriptor.addElement("static_resource_manager", true);
        pluginGeneratedSerialDescriptor.addElement("csProjectId", true);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    private JsonConfig$ProjectConfiguration$$serializer() {
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    @NotNull
    public KSerializer<?>[] childSerializers() {
        KSerializer<?>[] kSerializerArr = JsonConfig.ProjectConfiguration.$childSerializers;
        StringSerializer stringSerializer = StringSerializer.INSTANCE;
        IntSerializer intSerializer = IntSerializer.INSTANCE;
        KSerializer<?> kSerializer = kSerializerArr[10];
        KSerializer<?> nullable = BuiltinSerializersKt.getNullable(intSerializer);
        KSerializer<?> nullable2 = BuiltinSerializersKt.getNullable(stringSerializer);
        KSerializer<?> nullable3 = BuiltinSerializersKt.getNullable(JsonConfig$ApiErrorsV2$$serializer.INSTANCE);
        BooleanSerializer booleanSerializer = BooleanSerializer.INSTANCE;
        return new KSerializer[]{booleanSerializer, stringSerializer, FloatSerializer.INSTANCE, intSerializer, booleanSerializer, intSerializer, booleanSerializer, JsonConfig$ClientMode$$serializer.INSTANCE, JsonConfig$InAppConfig$$serializer.INSTANCE, JsonConfig$SessionReplay$$serializer.INSTANCE, kSerializer, nullable, nullable2, JsonConfig$ApiErrors$$serializer.INSTANCE, nullable3, JsonConfig$WebView$$serializer.INSTANCE, JsonConfig$StaticResourceManager$$serializer.INSTANCE, intSerializer};
    }

    @Override // kotlinx.serialization.DeserializationStrategy
    @NotNull
    public JsonConfig.ProjectConfiguration deserialize(Decoder decoder) {
        Object obj;
        Object objDecodeSerializableElement;
        Object objDecodeSerializableElement2;
        float f;
        Object objDecodeSerializableElement3;
        Object objDecodeNullableSerializableElement;
        Object objDecodeSerializableElement4;
        Object objDecodeNullableSerializableElement2;
        Object objDecodeNullableSerializableElement3;
        int i;
        String str;
        int iDecodeIntElement;
        boolean z;
        int i2;
        boolean z2;
        int i3;
        boolean z3;
        Object objDecodeSerializableElement5;
        Object objDecodeSerializableElement6;
        boolean zDecodeBooleanElement;
        String strDecodeStringElement;
        int iDecodeIntElement2;
        Object objDecodeNullableSerializableElement4;
        Object objDecodeSerializableElement7;
        Object objDecodeNullableSerializableElement5;
        Object objDecodeSerializableElement8;
        Object objDecodeNullableSerializableElement6;
        Object objDecodeSerializableElement9;
        float fDecodeFloatElement;
        Object objDecodeSerializableElement10;
        Object objDecodeSerializableElement11;
        Object obj2;
        int i4;
        Object obj3;
        Intrinsics.checkNotNullParameter(decoder, "decoder");
        SerialDescriptor descriptor2 = getDescriptor();
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(descriptor2);
        KSerializer[] kSerializerArr = JsonConfig.ProjectConfiguration.$childSerializers;
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            boolean zDecodeBooleanElement2 = compositeDecoderBeginStructure.decodeBooleanElement(descriptor2, 0);
            String strDecodeStringElement2 = compositeDecoderBeginStructure.decodeStringElement(descriptor2, 1);
            float fDecodeFloatElement2 = compositeDecoderBeginStructure.decodeFloatElement(descriptor2, 2);
            int iDecodeIntElement3 = compositeDecoderBeginStructure.decodeIntElement(descriptor2, 3);
            boolean zDecodeBooleanElement3 = compositeDecoderBeginStructure.decodeBooleanElement(descriptor2, 4);
            int iDecodeIntElement4 = compositeDecoderBeginStructure.decodeIntElement(descriptor2, 5);
            boolean zDecodeBooleanElement4 = compositeDecoderBeginStructure.decodeBooleanElement(descriptor2, 6);
            objDecodeSerializableElement6 = compositeDecoderBeginStructure.decodeSerializableElement(descriptor2, 7, JsonConfig$ClientMode$$serializer.INSTANCE, null);
            objDecodeSerializableElement2 = compositeDecoderBeginStructure.decodeSerializableElement(descriptor2, 8, JsonConfig$InAppConfig$$serializer.INSTANCE, null);
            objDecodeSerializableElement5 = compositeDecoderBeginStructure.decodeSerializableElement(descriptor2, 9, JsonConfig$SessionReplay$$serializer.INSTANCE, null);
            Object objDecodeSerializableElement12 = compositeDecoderBeginStructure.decodeSerializableElement(descriptor2, 10, kSerializerArr[10], null);
            objDecodeNullableSerializableElement3 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 11, IntSerializer.INSTANCE, null);
            objDecodeNullableSerializableElement2 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 12, StringSerializer.INSTANCE, null);
            objDecodeSerializableElement4 = compositeDecoderBeginStructure.decodeSerializableElement(descriptor2, 13, JsonConfig$ApiErrors$$serializer.INSTANCE, null);
            objDecodeNullableSerializableElement = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 14, JsonConfig$ApiErrorsV2$$serializer.INSTANCE, null);
            objDecodeSerializableElement = compositeDecoderBeginStructure.decodeSerializableElement(descriptor2, 15, JsonConfig$WebView$$serializer.INSTANCE, null);
            objDecodeSerializableElement3 = compositeDecoderBeginStructure.decodeSerializableElement(descriptor2, 16, JsonConfig$StaticResourceManager$$serializer.INSTANCE, null);
            z3 = zDecodeBooleanElement2;
            f = fDecodeFloatElement2;
            str = strDecodeStringElement2;
            i = iDecodeIntElement3;
            iDecodeIntElement = compositeDecoderBeginStructure.decodeIntElement(descriptor2, 17);
            z = zDecodeBooleanElement4;
            i2 = iDecodeIntElement4;
            z2 = zDecodeBooleanElement3;
            i3 = 262143;
            obj = objDecodeSerializableElement12;
        } else {
            boolean z4 = true;
            int i5 = 0;
            int iDecodeIntElement5 = 0;
            boolean zDecodeBooleanElement5 = false;
            int iDecodeIntElement6 = 0;
            boolean zDecodeBooleanElement6 = false;
            int i6 = 0;
            Object objDecodeSerializableElement13 = null;
            Object obj4 = null;
            Object obj5 = null;
            Object obj6 = null;
            Object obj7 = null;
            Object obj8 = null;
            Object obj9 = null;
            obj = null;
            Object obj10 = null;
            String str2 = null;
            Object obj11 = null;
            float f2 = 0.0f;
            boolean z5 = false;
            while (z4) {
                int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(descriptor2);
                switch (iDecodeElementIndex) {
                    case -1:
                        zDecodeBooleanElement = z5;
                        z4 = false;
                        z5 = zDecodeBooleanElement;
                    case 0:
                        zDecodeBooleanElement = compositeDecoderBeginStructure.decodeBooleanElement(descriptor2, 0);
                        strDecodeStringElement = str2;
                        iDecodeIntElement2 = i5;
                        objDecodeNullableSerializableElement4 = obj10;
                        objDecodeSerializableElement7 = obj;
                        objDecodeNullableSerializableElement5 = obj9;
                        objDecodeSerializableElement8 = obj8;
                        objDecodeNullableSerializableElement6 = obj7;
                        objDecodeSerializableElement9 = obj6;
                        fDecodeFloatElement = f2;
                        objDecodeSerializableElement10 = obj11;
                        objDecodeSerializableElement11 = obj5;
                        obj2 = obj4;
                        i4 = 1;
                        i6 |= i4;
                        obj4 = obj2;
                        obj5 = objDecodeSerializableElement11;
                        obj11 = objDecodeSerializableElement10;
                        f2 = fDecodeFloatElement;
                        obj6 = objDecodeSerializableElement9;
                        obj7 = objDecodeNullableSerializableElement6;
                        obj8 = objDecodeSerializableElement8;
                        obj9 = objDecodeNullableSerializableElement5;
                        obj = objDecodeSerializableElement7;
                        obj10 = objDecodeNullableSerializableElement4;
                        i5 = iDecodeIntElement2;
                        str2 = strDecodeStringElement;
                        z5 = zDecodeBooleanElement;
                    case 1:
                        zDecodeBooleanElement = z5;
                        strDecodeStringElement = compositeDecoderBeginStructure.decodeStringElement(descriptor2, 1);
                        iDecodeIntElement2 = i5;
                        objDecodeNullableSerializableElement4 = obj10;
                        objDecodeSerializableElement7 = obj;
                        objDecodeNullableSerializableElement5 = obj9;
                        objDecodeSerializableElement8 = obj8;
                        objDecodeNullableSerializableElement6 = obj7;
                        objDecodeSerializableElement9 = obj6;
                        fDecodeFloatElement = f2;
                        objDecodeSerializableElement10 = obj11;
                        objDecodeSerializableElement11 = obj5;
                        obj2 = obj4;
                        i4 = 2;
                        i6 |= i4;
                        obj4 = obj2;
                        obj5 = objDecodeSerializableElement11;
                        obj11 = objDecodeSerializableElement10;
                        f2 = fDecodeFloatElement;
                        obj6 = objDecodeSerializableElement9;
                        obj7 = objDecodeNullableSerializableElement6;
                        obj8 = objDecodeSerializableElement8;
                        obj9 = objDecodeNullableSerializableElement5;
                        obj = objDecodeSerializableElement7;
                        obj10 = objDecodeNullableSerializableElement4;
                        i5 = iDecodeIntElement2;
                        str2 = strDecodeStringElement;
                        z5 = zDecodeBooleanElement;
                    case 2:
                        zDecodeBooleanElement = z5;
                        strDecodeStringElement = str2;
                        objDecodeSerializableElement10 = obj11;
                        iDecodeIntElement2 = i5;
                        objDecodeSerializableElement11 = obj5;
                        objDecodeNullableSerializableElement4 = obj10;
                        obj2 = obj4;
                        objDecodeSerializableElement7 = obj;
                        i4 = 4;
                        objDecodeNullableSerializableElement5 = obj9;
                        objDecodeSerializableElement8 = obj8;
                        objDecodeNullableSerializableElement6 = obj7;
                        objDecodeSerializableElement9 = obj6;
                        fDecodeFloatElement = compositeDecoderBeginStructure.decodeFloatElement(descriptor2, 2);
                        i6 |= i4;
                        obj4 = obj2;
                        obj5 = objDecodeSerializableElement11;
                        obj11 = objDecodeSerializableElement10;
                        f2 = fDecodeFloatElement;
                        obj6 = objDecodeSerializableElement9;
                        obj7 = objDecodeNullableSerializableElement6;
                        obj8 = objDecodeSerializableElement8;
                        obj9 = objDecodeNullableSerializableElement5;
                        obj = objDecodeSerializableElement7;
                        obj10 = objDecodeNullableSerializableElement4;
                        i5 = iDecodeIntElement2;
                        str2 = strDecodeStringElement;
                        z5 = zDecodeBooleanElement;
                    case 3:
                        zDecodeBooleanElement = z5;
                        strDecodeStringElement = str2;
                        iDecodeIntElement2 = compositeDecoderBeginStructure.decodeIntElement(descriptor2, 3);
                        objDecodeNullableSerializableElement4 = obj10;
                        objDecodeSerializableElement7 = obj;
                        objDecodeNullableSerializableElement5 = obj9;
                        objDecodeSerializableElement8 = obj8;
                        objDecodeNullableSerializableElement6 = obj7;
                        objDecodeSerializableElement9 = obj6;
                        fDecodeFloatElement = f2;
                        objDecodeSerializableElement10 = obj11;
                        objDecodeSerializableElement11 = obj5;
                        obj2 = obj4;
                        i4 = 8;
                        i6 |= i4;
                        obj4 = obj2;
                        obj5 = objDecodeSerializableElement11;
                        obj11 = objDecodeSerializableElement10;
                        f2 = fDecodeFloatElement;
                        obj6 = objDecodeSerializableElement9;
                        obj7 = objDecodeNullableSerializableElement6;
                        obj8 = objDecodeSerializableElement8;
                        obj9 = objDecodeNullableSerializableElement5;
                        obj = objDecodeSerializableElement7;
                        obj10 = objDecodeNullableSerializableElement4;
                        i5 = iDecodeIntElement2;
                        str2 = strDecodeStringElement;
                        z5 = zDecodeBooleanElement;
                    case 4:
                        zDecodeBooleanElement = z5;
                        zDecodeBooleanElement6 = compositeDecoderBeginStructure.decodeBooleanElement(descriptor2, 4);
                        strDecodeStringElement = str2;
                        iDecodeIntElement2 = i5;
                        objDecodeNullableSerializableElement4 = obj10;
                        objDecodeSerializableElement7 = obj;
                        objDecodeNullableSerializableElement5 = obj9;
                        objDecodeSerializableElement8 = obj8;
                        objDecodeNullableSerializableElement6 = obj7;
                        objDecodeSerializableElement9 = obj6;
                        fDecodeFloatElement = f2;
                        objDecodeSerializableElement10 = obj11;
                        objDecodeSerializableElement11 = obj5;
                        obj2 = obj4;
                        i4 = 16;
                        i6 |= i4;
                        obj4 = obj2;
                        obj5 = objDecodeSerializableElement11;
                        obj11 = objDecodeSerializableElement10;
                        f2 = fDecodeFloatElement;
                        obj6 = objDecodeSerializableElement9;
                        obj7 = objDecodeNullableSerializableElement6;
                        obj8 = objDecodeSerializableElement8;
                        obj9 = objDecodeNullableSerializableElement5;
                        obj = objDecodeSerializableElement7;
                        obj10 = objDecodeNullableSerializableElement4;
                        i5 = iDecodeIntElement2;
                        str2 = strDecodeStringElement;
                        z5 = zDecodeBooleanElement;
                    case 5:
                        zDecodeBooleanElement = z5;
                        iDecodeIntElement6 = compositeDecoderBeginStructure.decodeIntElement(descriptor2, 5);
                        strDecodeStringElement = str2;
                        iDecodeIntElement2 = i5;
                        objDecodeNullableSerializableElement4 = obj10;
                        objDecodeSerializableElement7 = obj;
                        objDecodeNullableSerializableElement5 = obj9;
                        objDecodeSerializableElement8 = obj8;
                        objDecodeNullableSerializableElement6 = obj7;
                        objDecodeSerializableElement9 = obj6;
                        fDecodeFloatElement = f2;
                        objDecodeSerializableElement10 = obj11;
                        objDecodeSerializableElement11 = obj5;
                        obj2 = obj4;
                        i4 = 32;
                        i6 |= i4;
                        obj4 = obj2;
                        obj5 = objDecodeSerializableElement11;
                        obj11 = objDecodeSerializableElement10;
                        f2 = fDecodeFloatElement;
                        obj6 = objDecodeSerializableElement9;
                        obj7 = objDecodeNullableSerializableElement6;
                        obj8 = objDecodeSerializableElement8;
                        obj9 = objDecodeNullableSerializableElement5;
                        obj = objDecodeSerializableElement7;
                        obj10 = objDecodeNullableSerializableElement4;
                        i5 = iDecodeIntElement2;
                        str2 = strDecodeStringElement;
                        z5 = zDecodeBooleanElement;
                    case 6:
                        zDecodeBooleanElement = z5;
                        zDecodeBooleanElement5 = compositeDecoderBeginStructure.decodeBooleanElement(descriptor2, 6);
                        strDecodeStringElement = str2;
                        iDecodeIntElement2 = i5;
                        objDecodeNullableSerializableElement4 = obj10;
                        objDecodeSerializableElement7 = obj;
                        objDecodeNullableSerializableElement5 = obj9;
                        objDecodeSerializableElement8 = obj8;
                        objDecodeNullableSerializableElement6 = obj7;
                        objDecodeSerializableElement9 = obj6;
                        fDecodeFloatElement = f2;
                        objDecodeSerializableElement10 = obj11;
                        objDecodeSerializableElement11 = obj5;
                        obj2 = obj4;
                        i4 = 64;
                        i6 |= i4;
                        obj4 = obj2;
                        obj5 = objDecodeSerializableElement11;
                        obj11 = objDecodeSerializableElement10;
                        f2 = fDecodeFloatElement;
                        obj6 = objDecodeSerializableElement9;
                        obj7 = objDecodeNullableSerializableElement6;
                        obj8 = objDecodeSerializableElement8;
                        obj9 = objDecodeNullableSerializableElement5;
                        obj = objDecodeSerializableElement7;
                        obj10 = objDecodeNullableSerializableElement4;
                        i5 = iDecodeIntElement2;
                        str2 = strDecodeStringElement;
                        z5 = zDecodeBooleanElement;
                    case 7:
                        zDecodeBooleanElement = z5;
                        strDecodeStringElement = str2;
                        iDecodeIntElement2 = i5;
                        objDecodeNullableSerializableElement4 = obj10;
                        objDecodeSerializableElement7 = obj;
                        objDecodeNullableSerializableElement5 = obj9;
                        objDecodeSerializableElement8 = obj8;
                        objDecodeNullableSerializableElement6 = obj7;
                        objDecodeSerializableElement9 = obj6;
                        fDecodeFloatElement = f2;
                        objDecodeSerializableElement10 = compositeDecoderBeginStructure.decodeSerializableElement(descriptor2, 7, JsonConfig$ClientMode$$serializer.INSTANCE, obj11);
                        obj3 = obj5;
                        obj2 = obj4;
                        i4 = 128;
                        objDecodeSerializableElement11 = obj3;
                        i6 |= i4;
                        obj4 = obj2;
                        obj5 = objDecodeSerializableElement11;
                        obj11 = objDecodeSerializableElement10;
                        f2 = fDecodeFloatElement;
                        obj6 = objDecodeSerializableElement9;
                        obj7 = objDecodeNullableSerializableElement6;
                        obj8 = objDecodeSerializableElement8;
                        obj9 = objDecodeNullableSerializableElement5;
                        obj = objDecodeSerializableElement7;
                        obj10 = objDecodeNullableSerializableElement4;
                        i5 = iDecodeIntElement2;
                        str2 = strDecodeStringElement;
                        z5 = zDecodeBooleanElement;
                    case 8:
                        zDecodeBooleanElement = z5;
                        strDecodeStringElement = str2;
                        iDecodeIntElement2 = i5;
                        objDecodeNullableSerializableElement4 = obj10;
                        objDecodeSerializableElement7 = obj;
                        objDecodeNullableSerializableElement5 = obj9;
                        objDecodeSerializableElement8 = obj8;
                        objDecodeNullableSerializableElement6 = obj7;
                        objDecodeSerializableElement9 = obj6;
                        fDecodeFloatElement = f2;
                        objDecodeSerializableElement10 = obj11;
                        objDecodeSerializableElement11 = compositeDecoderBeginStructure.decodeSerializableElement(descriptor2, 8, JsonConfig$InAppConfig$$serializer.INSTANCE, obj5);
                        obj2 = obj4;
                        i4 = 256;
                        i6 |= i4;
                        obj4 = obj2;
                        obj5 = objDecodeSerializableElement11;
                        obj11 = objDecodeSerializableElement10;
                        f2 = fDecodeFloatElement;
                        obj6 = objDecodeSerializableElement9;
                        obj7 = objDecodeNullableSerializableElement6;
                        obj8 = objDecodeSerializableElement8;
                        obj9 = objDecodeNullableSerializableElement5;
                        obj = objDecodeSerializableElement7;
                        obj10 = objDecodeNullableSerializableElement4;
                        i5 = iDecodeIntElement2;
                        str2 = strDecodeStringElement;
                        z5 = zDecodeBooleanElement;
                    case 9:
                        zDecodeBooleanElement = z5;
                        Object objDecodeSerializableElement14 = compositeDecoderBeginStructure.decodeSerializableElement(descriptor2, 9, JsonConfig$SessionReplay$$serializer.INSTANCE, obj4);
                        i4 = 512;
                        strDecodeStringElement = str2;
                        iDecodeIntElement2 = i5;
                        objDecodeNullableSerializableElement4 = obj10;
                        objDecodeSerializableElement7 = obj;
                        objDecodeNullableSerializableElement5 = obj9;
                        objDecodeSerializableElement8 = obj8;
                        objDecodeNullableSerializableElement6 = obj7;
                        objDecodeSerializableElement9 = obj6;
                        fDecodeFloatElement = f2;
                        objDecodeSerializableElement10 = obj11;
                        objDecodeSerializableElement11 = obj5;
                        obj2 = objDecodeSerializableElement14;
                        i6 |= i4;
                        obj4 = obj2;
                        obj5 = objDecodeSerializableElement11;
                        obj11 = objDecodeSerializableElement10;
                        f2 = fDecodeFloatElement;
                        obj6 = objDecodeSerializableElement9;
                        obj7 = objDecodeNullableSerializableElement6;
                        obj8 = objDecodeSerializableElement8;
                        obj9 = objDecodeNullableSerializableElement5;
                        obj = objDecodeSerializableElement7;
                        obj10 = objDecodeNullableSerializableElement4;
                        i5 = iDecodeIntElement2;
                        str2 = strDecodeStringElement;
                        z5 = zDecodeBooleanElement;
                    case 10:
                        zDecodeBooleanElement = z5;
                        strDecodeStringElement = str2;
                        iDecodeIntElement2 = i5;
                        objDecodeNullableSerializableElement4 = obj10;
                        objDecodeSerializableElement7 = compositeDecoderBeginStructure.decodeSerializableElement(descriptor2, 10, kSerializerArr[10], obj);
                        obj3 = obj5;
                        obj2 = obj4;
                        i4 = 1024;
                        objDecodeNullableSerializableElement5 = obj9;
                        objDecodeSerializableElement8 = obj8;
                        objDecodeNullableSerializableElement6 = obj7;
                        objDecodeSerializableElement9 = obj6;
                        fDecodeFloatElement = f2;
                        objDecodeSerializableElement10 = obj11;
                        objDecodeSerializableElement11 = obj3;
                        i6 |= i4;
                        obj4 = obj2;
                        obj5 = objDecodeSerializableElement11;
                        obj11 = objDecodeSerializableElement10;
                        f2 = fDecodeFloatElement;
                        obj6 = objDecodeSerializableElement9;
                        obj7 = objDecodeNullableSerializableElement6;
                        obj8 = objDecodeSerializableElement8;
                        obj9 = objDecodeNullableSerializableElement5;
                        obj = objDecodeSerializableElement7;
                        obj10 = objDecodeNullableSerializableElement4;
                        i5 = iDecodeIntElement2;
                        str2 = strDecodeStringElement;
                        z5 = zDecodeBooleanElement;
                    case 11:
                        zDecodeBooleanElement = z5;
                        strDecodeStringElement = str2;
                        iDecodeIntElement2 = i5;
                        objDecodeNullableSerializableElement4 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 11, IntSerializer.INSTANCE, obj10);
                        obj3 = obj5;
                        obj2 = obj4;
                        i4 = 2048;
                        objDecodeSerializableElement7 = obj;
                        objDecodeNullableSerializableElement5 = obj9;
                        objDecodeSerializableElement8 = obj8;
                        objDecodeNullableSerializableElement6 = obj7;
                        objDecodeSerializableElement9 = obj6;
                        fDecodeFloatElement = f2;
                        objDecodeSerializableElement10 = obj11;
                        objDecodeSerializableElement11 = obj3;
                        i6 |= i4;
                        obj4 = obj2;
                        obj5 = objDecodeSerializableElement11;
                        obj11 = objDecodeSerializableElement10;
                        f2 = fDecodeFloatElement;
                        obj6 = objDecodeSerializableElement9;
                        obj7 = objDecodeNullableSerializableElement6;
                        obj8 = objDecodeSerializableElement8;
                        obj9 = objDecodeNullableSerializableElement5;
                        obj = objDecodeSerializableElement7;
                        obj10 = objDecodeNullableSerializableElement4;
                        i5 = iDecodeIntElement2;
                        str2 = strDecodeStringElement;
                        z5 = zDecodeBooleanElement;
                    case 12:
                        zDecodeBooleanElement = z5;
                        strDecodeStringElement = str2;
                        iDecodeIntElement2 = i5;
                        objDecodeNullableSerializableElement4 = obj10;
                        objDecodeSerializableElement7 = obj;
                        objDecodeNullableSerializableElement5 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 12, StringSerializer.INSTANCE, obj9);
                        obj3 = obj5;
                        obj2 = obj4;
                        i4 = 4096;
                        objDecodeSerializableElement8 = obj8;
                        objDecodeNullableSerializableElement6 = obj7;
                        objDecodeSerializableElement9 = obj6;
                        fDecodeFloatElement = f2;
                        objDecodeSerializableElement10 = obj11;
                        objDecodeSerializableElement11 = obj3;
                        i6 |= i4;
                        obj4 = obj2;
                        obj5 = objDecodeSerializableElement11;
                        obj11 = objDecodeSerializableElement10;
                        f2 = fDecodeFloatElement;
                        obj6 = objDecodeSerializableElement9;
                        obj7 = objDecodeNullableSerializableElement6;
                        obj8 = objDecodeSerializableElement8;
                        obj9 = objDecodeNullableSerializableElement5;
                        obj = objDecodeSerializableElement7;
                        obj10 = objDecodeNullableSerializableElement4;
                        i5 = iDecodeIntElement2;
                        str2 = strDecodeStringElement;
                        z5 = zDecodeBooleanElement;
                    case 13:
                        zDecodeBooleanElement = z5;
                        strDecodeStringElement = str2;
                        iDecodeIntElement2 = i5;
                        objDecodeNullableSerializableElement4 = obj10;
                        objDecodeSerializableElement7 = obj;
                        objDecodeNullableSerializableElement5 = obj9;
                        objDecodeSerializableElement8 = compositeDecoderBeginStructure.decodeSerializableElement(descriptor2, 13, JsonConfig$ApiErrors$$serializer.INSTANCE, obj8);
                        obj3 = obj5;
                        obj2 = obj4;
                        i4 = 8192;
                        objDecodeNullableSerializableElement6 = obj7;
                        objDecodeSerializableElement9 = obj6;
                        fDecodeFloatElement = f2;
                        objDecodeSerializableElement10 = obj11;
                        objDecodeSerializableElement11 = obj3;
                        i6 |= i4;
                        obj4 = obj2;
                        obj5 = objDecodeSerializableElement11;
                        obj11 = objDecodeSerializableElement10;
                        f2 = fDecodeFloatElement;
                        obj6 = objDecodeSerializableElement9;
                        obj7 = objDecodeNullableSerializableElement6;
                        obj8 = objDecodeSerializableElement8;
                        obj9 = objDecodeNullableSerializableElement5;
                        obj = objDecodeSerializableElement7;
                        obj10 = objDecodeNullableSerializableElement4;
                        i5 = iDecodeIntElement2;
                        str2 = strDecodeStringElement;
                        z5 = zDecodeBooleanElement;
                    case 14:
                        zDecodeBooleanElement = z5;
                        strDecodeStringElement = str2;
                        iDecodeIntElement2 = i5;
                        objDecodeNullableSerializableElement4 = obj10;
                        objDecodeSerializableElement7 = obj;
                        objDecodeNullableSerializableElement5 = obj9;
                        objDecodeSerializableElement8 = obj8;
                        objDecodeNullableSerializableElement6 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 14, JsonConfig$ApiErrorsV2$$serializer.INSTANCE, obj7);
                        obj3 = obj5;
                        obj2 = obj4;
                        i4 = 16384;
                        objDecodeSerializableElement9 = obj6;
                        fDecodeFloatElement = f2;
                        objDecodeSerializableElement10 = obj11;
                        objDecodeSerializableElement11 = obj3;
                        i6 |= i4;
                        obj4 = obj2;
                        obj5 = objDecodeSerializableElement11;
                        obj11 = objDecodeSerializableElement10;
                        f2 = fDecodeFloatElement;
                        obj6 = objDecodeSerializableElement9;
                        obj7 = objDecodeNullableSerializableElement6;
                        obj8 = objDecodeSerializableElement8;
                        obj9 = objDecodeNullableSerializableElement5;
                        obj = objDecodeSerializableElement7;
                        obj10 = objDecodeNullableSerializableElement4;
                        i5 = iDecodeIntElement2;
                        str2 = strDecodeStringElement;
                        z5 = zDecodeBooleanElement;
                    case 15:
                        zDecodeBooleanElement = z5;
                        objDecodeSerializableElement13 = compositeDecoderBeginStructure.decodeSerializableElement(descriptor2, 15, JsonConfig$WebView$$serializer.INSTANCE, objDecodeSerializableElement13);
                        strDecodeStringElement = str2;
                        iDecodeIntElement2 = i5;
                        objDecodeNullableSerializableElement4 = obj10;
                        objDecodeSerializableElement7 = obj;
                        objDecodeNullableSerializableElement5 = obj9;
                        objDecodeSerializableElement8 = obj8;
                        objDecodeNullableSerializableElement6 = obj7;
                        objDecodeSerializableElement9 = obj6;
                        fDecodeFloatElement = f2;
                        objDecodeSerializableElement10 = obj11;
                        objDecodeSerializableElement11 = obj5;
                        obj2 = obj4;
                        i4 = 32768;
                        i6 |= i4;
                        obj4 = obj2;
                        obj5 = objDecodeSerializableElement11;
                        obj11 = objDecodeSerializableElement10;
                        f2 = fDecodeFloatElement;
                        obj6 = objDecodeSerializableElement9;
                        obj7 = objDecodeNullableSerializableElement6;
                        obj8 = objDecodeSerializableElement8;
                        obj9 = objDecodeNullableSerializableElement5;
                        obj = objDecodeSerializableElement7;
                        obj10 = objDecodeNullableSerializableElement4;
                        i5 = iDecodeIntElement2;
                        str2 = strDecodeStringElement;
                        z5 = zDecodeBooleanElement;
                    case 16:
                        zDecodeBooleanElement = z5;
                        strDecodeStringElement = str2;
                        iDecodeIntElement2 = i5;
                        objDecodeNullableSerializableElement4 = obj10;
                        objDecodeSerializableElement7 = obj;
                        objDecodeNullableSerializableElement5 = obj9;
                        objDecodeSerializableElement8 = obj8;
                        objDecodeNullableSerializableElement6 = obj7;
                        objDecodeSerializableElement9 = compositeDecoderBeginStructure.decodeSerializableElement(descriptor2, 16, JsonConfig$StaticResourceManager$$serializer.INSTANCE, obj6);
                        obj3 = obj5;
                        obj2 = obj4;
                        i4 = 65536;
                        fDecodeFloatElement = f2;
                        objDecodeSerializableElement10 = obj11;
                        objDecodeSerializableElement11 = obj3;
                        i6 |= i4;
                        obj4 = obj2;
                        obj5 = objDecodeSerializableElement11;
                        obj11 = objDecodeSerializableElement10;
                        f2 = fDecodeFloatElement;
                        obj6 = objDecodeSerializableElement9;
                        obj7 = objDecodeNullableSerializableElement6;
                        obj8 = objDecodeSerializableElement8;
                        obj9 = objDecodeNullableSerializableElement5;
                        obj = objDecodeSerializableElement7;
                        obj10 = objDecodeNullableSerializableElement4;
                        i5 = iDecodeIntElement2;
                        str2 = strDecodeStringElement;
                        z5 = zDecodeBooleanElement;
                    case 17:
                        iDecodeIntElement5 = compositeDecoderBeginStructure.decodeIntElement(descriptor2, 17);
                        i6 |= 131072;
                    default:
                        throw new UnknownFieldException(iDecodeElementIndex);
                }
            }
            objDecodeSerializableElement = objDecodeSerializableElement13;
            objDecodeSerializableElement2 = obj5;
            f = f2;
            objDecodeSerializableElement3 = obj6;
            objDecodeNullableSerializableElement = obj7;
            objDecodeSerializableElement4 = obj8;
            objDecodeNullableSerializableElement2 = obj9;
            objDecodeNullableSerializableElement3 = obj10;
            i = i5;
            str = str2;
            iDecodeIntElement = iDecodeIntElement5;
            z = zDecodeBooleanElement5;
            i2 = iDecodeIntElement6;
            z2 = zDecodeBooleanElement6;
            i3 = i6;
            z3 = z5;
            objDecodeSerializableElement5 = obj4;
            objDecodeSerializableElement6 = obj11;
        }
        compositeDecoderBeginStructure.endStructure(descriptor2);
        return new JsonConfig.ProjectConfiguration(i3, z3, str, f, i, z2, i2, z, (JsonConfig.ClientMode) objDecodeSerializableElement6, (JsonConfig.InAppConfig) objDecodeSerializableElement2, (JsonConfig.SessionReplay) objDecodeSerializableElement5, (List) obj, (Integer) objDecodeNullableSerializableElement3, (String) objDecodeNullableSerializableElement2, (JsonConfig.ApiErrors) objDecodeSerializableElement4, (JsonConfig.ApiErrorsV2) objDecodeNullableSerializableElement, (JsonConfig.WebView) objDecodeSerializableElement, (JsonConfig.StaticResourceManager) objDecodeSerializableElement3, iDecodeIntElement, (SerializationConstructorMarker) null);
    }

    @Override // kotlinx.serialization.KSerializer, kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    @NotNull
    public SerialDescriptor getDescriptor() {
        return descriptor;
    }

    @Override // kotlinx.serialization.SerializationStrategy
    public void serialize(Encoder encoder, JsonConfig.ProjectConfiguration value) {
        Intrinsics.checkNotNullParameter(encoder, "encoder");
        Intrinsics.checkNotNullParameter(value, "value");
        SerialDescriptor descriptor2 = getDescriptor();
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(descriptor2);
        JsonConfig.ProjectConfiguration.write$Self(value, compositeEncoderBeginStructure, descriptor2);
        compositeEncoderBeginStructure.endStructure(descriptor2);
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    @NotNull
    public KSerializer<?>[] typeParametersSerializers() {
        return GeneratedSerializer.DefaultImpls.typeParametersSerializers(this);
    }
}
