package com.google.android.gms.measurement.internal;

import android.content.Context;
import ch.qos.logback.core.CoreConstants;
import ch.qos.logback.core.spi.ComponentTracker;
import com.google.android.gms.common.util.VisibleForTesting;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

@VisibleForTesting
/* loaded from: classes4.dex */
public final class zzaq {
    public static zzen<Long> zzaa;
    public static zzen<Integer> zzab;
    public static zzen<Long> zzac;
    public static zzen<Integer> zzad;
    public static zzen<Integer> zzae;
    public static zzen<Integer> zzaf;
    public static zzen<Integer> zzag;
    public static zzen<Integer> zzah;
    public static zzen<Long> zzai;
    public static zzen<Boolean> zzaj;
    public static zzen<String> zzak;
    public static zzen<Long> zzal;
    public static zzen<Integer> zzam;
    public static zzen<Double> zzan;
    public static zzen<Integer> zzao;
    public static zzen<Integer> zzap;
    public static zzen<Boolean> zzaq;
    public static zzen<Boolean> zzar;
    public static zzen<Boolean> zzas;
    public static zzen<Boolean> zzat;
    public static zzen<Boolean> zzau;
    public static zzen<Boolean> zzav;
    public static zzen<Boolean> zzaw;
    public static zzen<Boolean> zzax;
    public static zzen<Boolean> zzay;
    public static zzen<Boolean> zzaz;
    public static zzen<Boolean> zzba;
    public static zzen<Boolean> zzbb;
    public static zzen<Boolean> zzbc;
    public static zzen<Boolean> zzbd;
    public static zzen<Boolean> zzbe;
    public static zzen<Boolean> zzbf;
    public static zzen<Boolean> zzbg;
    public static zzen<Boolean> zzbh;
    public static zzen<Boolean> zzbi;
    public static zzen<Boolean> zzbj;
    public static zzen<Boolean> zzbk;
    public static zzen<Boolean> zzbl;
    public static zzen<Boolean> zzbm;
    public static zzen<Boolean> zzbn;
    public static zzen<Boolean> zzbo;
    public static zzen<Boolean> zzbp;
    public static zzen<Boolean> zzbq;
    public static zzen<Boolean> zzbr;
    public static zzen<Boolean> zzbs;
    public static zzen<Boolean> zzbt;
    public static zzen<Boolean> zzbu;
    public static zzen<Boolean> zzbv;
    public static zzen<Boolean> zzbw;
    public static zzen<Boolean> zzbx;
    public static zzen<Boolean> zzby;
    public static zzen<Boolean> zzbz;
    public static zzen<Boolean> zzca;
    public static zzen<Boolean> zzcb;
    public static zzen<Boolean> zzcc;
    public static zzen<Boolean> zzcd;
    public static zzen<Boolean> zzce;
    public static zzen<Boolean> zzcf;
    public static zzen<Boolean> zzcg;
    public static zzen<Boolean> zzch;
    public static zzen<Boolean> zzci;
    public static zzen<Boolean> zzcj;
    public static zzen<Boolean> zzck;
    public static zzen<Boolean> zzcl;
    public static zzen<Boolean> zzcm;
    public static zzen<Boolean> zzcn;
    public static zzen<Boolean> zzco;
    public static zzen<Boolean> zzcp;
    public static zzen<Boolean> zzcq;
    public static zzen<Long> zzcr;
    public static zzen<Boolean> zzcs;
    private static zzen zzcv;
    private static zzen zzcw;
    public static zzen<Long> zzy;
    public static zzen<Long> zzz;
    private static List zzct = Collections.synchronizedList(new ArrayList());
    private static Set zzcu = Collections.synchronizedSet(new HashSet());
    public static zzen<Long> zza = zza("measurement.ad_id_cache_time", 10000L, 10000L, zzat.zza);
    public static zzen<Long> zzb = zza("measurement.monitoring.sample_period_millis", 86400000L, 86400000L, zzas.zza);
    public static zzen<Long> zzc = zza("measurement.config.cache_time", 86400000L, 3600000L, zzbf.zza);
    public static zzen<String> zzd = zza("measurement.config.url_scheme", "https", "https", zzbo.zza);
    public static zzen<String> zze = zza("measurement.config.url_authority", "app-measurement.com", "app-measurement.com", zzcb.zza);
    public static zzen<Integer> zzf = zza("measurement.upload.max_bundles", 100, 100, zzck.zza);
    public static zzen<Integer> zzg = zza("measurement.upload.max_batch_size", 65536, 65536, zzcx.zza);
    public static zzen<Integer> zzh = zza("measurement.upload.max_bundle_size", 65536, 65536, zzdg.zza);
    public static zzen<Integer> zzi = zza("measurement.upload.max_events_per_bundle", 1000, 1000, zzdt.zza);
    public static zzen<Integer> zzj = zza("measurement.upload.max_events_per_day", 100000, 100000, zzec.zza);
    public static zzen<Integer> zzk = zza("measurement.upload.max_error_events_per_day", 1000, 1000, zzav.zza);
    public static zzen<Integer> zzl = zza("measurement.upload.max_public_events_per_day", 50000, 50000, zzau.zza);
    public static zzen<Integer> zzm = zza("measurement.upload.max_conversions_per_day", 10000, 10000, zzax.zza);
    public static zzen<Integer> zzn = zza("measurement.upload.max_realtime_events_per_day", 10, 10, zzaw.zza);
    public static zzen<Integer> zzo = zza("measurement.store.max_stored_events_per_app", 100000, 100000, zzaz.zza);
    public static zzen<String> zzp = zza("measurement.upload.url", "https://app-measurement.com/a", "https://app-measurement.com/a", zzay.zza);
    public static zzen<Long> zzq = zza("measurement.upload.backoff_period", 43200000L, 43200000L, zzbb.zza);
    public static zzen<Long> zzr = zza("measurement.upload.window_interval", 3600000L, 3600000L, zzba.zza);
    public static zzen<Long> zzs = zza("measurement.upload.interval", 3600000L, 3600000L, zzbd.zza);
    public static zzen<Long> zzt = zza("measurement.upload.realtime_upload_interval", 10000L, 10000L, zzbc.zza);
    public static zzen<Long> zzu = zza("measurement.upload.debug_upload_interval", 1000L, 1000L, zzbe.zza);
    public static zzen<Long> zzv = zza("measurement.upload.minimum_delay", 500L, 500L, zzbh.zza);
    public static zzen<Long> zzw = zza("measurement.alarm_manager.minimum_interval", 60000L, 60000L, zzbg.zza);
    public static zzen<Long> zzx = zza("measurement.upload.stale_data_deletion_interval", 86400000L, 86400000L, zzbj.zza);

    public static Map<String, String> zza(Context context) {
        com.google.android.gms.internal.measurement.zzch zzchVarZza = com.google.android.gms.internal.measurement.zzch.zza(context.getContentResolver(), com.google.android.gms.internal.measurement.zzcw.zza("com.google.android.gms.measurement"));
        return zzchVarZza == null ? Collections.emptyMap() : zzchVarZza.zza();
    }

    private static zzen zza(String str, Object obj, Object obj2, zzel zzelVar) {
        zzen zzenVar = new zzen(str, obj, obj2, zzelVar);
        zzct.add(zzenVar);
        return zzenVar;
    }

    static {
        Long lValueOf = Long.valueOf(CoreConstants.MILLIS_IN_ONE_WEEK);
        zzy = zza("measurement.upload.refresh_blacklisted_config_interval", lValueOf, lValueOf, zzbi.zza);
        zzz = zza("measurement.upload.initial_upload_delay_time", 15000L, 15000L, zzbl.zza);
        Long lValueOf2 = Long.valueOf(ComponentTracker.DEFAULT_TIMEOUT);
        zzaa = zza("measurement.upload.retry_time", lValueOf2, lValueOf2, zzbk.zza);
        zzab = zza("measurement.upload.retry_count", 6, 6, zzbn.zza);
        zzac = zza("measurement.upload.max_queue_time", 2419200000L, 2419200000L, zzbm.zza);
        zzad = zza("measurement.lifetimevalue.max_currency_tracked", 4, 4, zzbp.zza);
        zzae = zza("measurement.audience.filter_result_max_count", 200, 200, zzbr.zza);
        zzaf = zza("measurement.upload.max_public_user_properties", 25, 25, null);
        zzag = zza("measurement.upload.max_event_name_cardinality", 500, 500, null);
        zzah = zza("measurement.upload.max_public_event_params", 25, 25, null);
        zzai = zza("measurement.service_client.idle_disconnect_millis", 5000L, 5000L, zzbq.zza);
        Boolean bool = Boolean.FALSE;
        zzaj = zza("measurement.test.boolean_flag", bool, bool, zzbt.zza);
        zzak = zza("measurement.test.string_flag", "---", "---", zzbs.zza);
        zzal = zza("measurement.test.long_flag", -1L, -1L, zzbv.zza);
        zzam = zza("measurement.test.int_flag", -2, -2, zzbu.zza);
        Double dValueOf = Double.valueOf(-3.0d);
        zzan = zza("measurement.test.double_flag", dValueOf, dValueOf, zzbx.zza);
        zzao = zza("measurement.experiment.max_ids", 50, 50, zzbw.zza);
        zzap = zza("measurement.max_bundles_per_iteration", 2, 2, zzbz.zza);
        zzaq = zza("measurement.validation.internal_limits_internal_event_params", bool, bool, zzby.zza);
        Boolean bool2 = Boolean.TRUE;
        zzar = zza("measurement.referrer.enable_logging_install_referrer_cmp_from_apk", bool2, bool2, zzca.zza);
        zzas = zza("measurement.collection.firebase_global_collection_flag_enabled", bool2, bool2, zzcd.zza);
        zzat = zza("measurement.collection.efficient_engagement_reporting_enabled_2", bool2, bool2, zzcc.zza);
        zzau = zza("measurement.collection.redundant_engagement_removal_enabled", bool, bool, zzcf.zza);
        zzav = zza("measurement.client.freeride_engagement_fix", bool2, bool2, zzce.zza);
        zzaw = zza("measurement.experiment.enable_experiment_reporting", bool2, bool2, zzch.zza);
        zzax = zza("measurement.collection.log_event_and_bundle_v2", bool2, bool2, zzcg.zza);
        zzay = zza("measurement.quality.checksum", bool, bool, null);
        zzaz = zza("measurement.sdk.dynamite.allow_remote_dynamite2", bool, bool, zzcj.zza);
        zzba = zza("measurement.sdk.collection.validate_param_names_alphabetical", bool2, bool2, zzci.zza);
        zzbb = zza("measurement.collection.event_safelist", bool2, bool2, zzcl.zza);
        zzcv = zza("measurement.service.audience.invalidate_config_cache_after_app_unisntall", bool2, bool2, zzcn.zza);
        zzbc = zza("measurement.service.audience.fix_skip_audience_with_failed_filters", bool2, bool2, zzcm.zza);
        zzbd = zza("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", bool, bool, zzcp.zza);
        zzbe = zza("measurement.audience.refresh_event_count_filters_timestamp", bool, bool, zzco.zza);
        zzbf = zza("measurement.audience.use_bundle_timestamp_for_event_count_filters", bool, bool, zzcr.zza);
        zzbg = zza("measurement.sdk.collection.retrieve_deeplink_from_bow_2", bool2, bool2, zzcq.zza);
        zzbh = zza("measurement.sdk.collection.last_deep_link_referrer2", bool2, bool2, zzct.zza);
        zzbi = zza("measurement.sdk.collection.last_deep_link_referrer_campaign2", bool, bool, zzcs.zza);
        zzbj = zza("measurement.sdk.collection.last_gclid_from_referrer2", bool, bool, zzcv.zza);
        zzbk = zza("measurement.sdk.collection.enable_extend_user_property_size", bool2, bool2, zzcu.zza);
        zzbl = zza("measurement.upload.file_lock_state_check", bool, bool, zzcw.zza);
        zzbm = zza("measurement.sampling.calculate_bundle_timestamp_before_sampling", bool2, bool2, zzcz.zza);
        zzbn = zza("measurement.ga.ga_app_id", bool, bool, zzcy.zza);
        zzbo = zza("measurement.lifecycle.app_backgrounded_tracking", bool2, bool2, zzdb.zza);
        zzbp = zza("measurement.lifecycle.app_in_background_parameter", bool, bool, zzda.zza);
        zzbq = zza("measurement.integration.disable_firebase_instance_id", bool, bool, zzdd.zza);
        zzbr = zza("measurement.lifecycle.app_backgrounded_engagement", bool, bool, zzdc.zza);
        zzbs = zza("measurement.collection.service.update_with_analytics_fix", bool, bool, zzdf.zza);
        zzbt = zza("measurement.service.use_appinfo_modified", bool, bool, zzde.zza);
        zzbu = zza("measurement.client.firebase_feature_rollout.v1.enable", bool2, bool2, zzdh.zza);
        zzbv = zza("measurement.client.sessions.check_on_reset_and_enable2", bool2, bool2, zzdj.zza);
        zzbw = zza("measurement.config.string.always_update_disk_on_set", bool2, bool2, zzdi.zza);
        zzbx = zza("measurement.scheduler.task_thread.cleanup_on_exit", bool, bool, zzdl.zza);
        zzby = zza("measurement.upload.file_truncate_fix", bool, bool, zzdk.zza);
        zzbz = zza("measurement.engagement_time_main_thread", bool2, bool2, zzdn.zza);
        zzca = zza("measurement.sdk.referrer.delayed_install_referrer_api", bool, bool, zzdm.zza);
        zzcb = zza("measurement.sdk.screen.disabling_automatic_reporting", bool, bool, zzdp.zza);
        zzcc = zza("measurement.sdk.screen.manual_screen_view_logging", bool, bool, zzdo.zza);
        zzcd = zza("measurement.gold.enhanced_ecommerce.format_logs", bool2, bool2, zzdr.zza);
        zzce = zza("measurement.gold.enhanced_ecommerce.nested_param_daily_event_count", bool2, bool2, zzdq.zza);
        zzcf = zza("measurement.gold.enhanced_ecommerce.upload_nested_complex_events", bool2, bool2, zzds.zza);
        zzcg = zza("measurement.gold.enhanced_ecommerce.log_nested_complex_events", bool2, bool2, zzdv.zza);
        zzch = zza("measurement.gold.enhanced_ecommerce.updated_schema.client", bool2, bool2, zzdu.zza);
        zzci = zza("measurement.gold.enhanced_ecommerce.updated_schema.service", bool2, bool2, zzdx.zza);
        zzcw = zza("measurement.collection.synthetic_data_mitigation", bool, bool, zzdw.zza);
        zzcj = zza("measurement.service.configurable_service_limits", bool, bool, zzdz.zza);
        zzck = zza("measurement.client.configurable_service_limits", bool, bool, zzdy.zza);
        zzcl = zza("measurement.androidId.delete_feature", bool2, bool2, zzeb.zza);
        zzcm = zza("measurement.client.global_params.dev", bool, bool, zzea.zza);
        zzcn = zza("measurement.service.global_params", bool, bool, zzed.zza);
        zzco = zza("measurement.service.global_params_in_payload", bool2, bool2, zzef.zza);
        zzcp = zza("measurement.client.string_reader", bool2, bool2, zzee.zza);
        zzcq = zza("measurement.sdk.attribution.cache", bool2, bool2, zzeh.zza);
        zzcr = zza("measurement.sdk.attribution.cache.ttl", lValueOf, lValueOf, zzeg.zza);
        zzcs = zza("measurement.service.database_return_empty_collection", bool2, bool2, zzej.zza);
    }
}
